name: Trigger Game Functions

on:
  schedule:
    - cron: '* * * * *'

jobs:
  call-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up common variables
        run: |
          echo "API_URL=https://bdff1.playfabapi.com/Client/ExecuteCloudScript" >> $GITHUB_ENV
          echo "AUTH_HEADER=${{ 80A4A6D2C7894332-7FD9B6B01144357E-BABA47BAB1BEAB0F-BDFF1-8DDD59A5D7EA784-j+PpHTDVEWP3ysLkZAHGh7T9COzxWISQBDcpWz0GLYc= }}" >> $GITHUB_ENV
          echo 'PAYLOAD_BASE={
            "CustomTags": null,
            "FunctionParameter": {
              "roomType": "QUICK_GAME",
              "playerIds": ["80A4A6D2C7894332", "F930D42AFE1ED60", "F930D42AFE1ED60", "F930D42AFE1ED60", "F930D42AFE1ED60", "F930D42AFE1ED60"]
            },
            "GeneratePlayStreamEvent": true,
            "RevisionSelection": null,
            "SpecificRevision": null,
            "AuthenticationContext": null
          }' >> $GITHUB_ENV

      - name: Call startNewMatch
        run: |
          curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -H "X-Authorization: $AUTH_HEADER" \
          -d "$(echo $PAYLOAD_BASE | jq --arg fn startNewMatch '. + {FunctionName: $fn}')"

      - name: Call decideSpecialRole
        run: |
          curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -H "X-Authorization: $AUTH_HEADER" \
          -d "$(echo $PAYLOAD_BASE | jq --arg fn decideSpecialRole '. + {FunctionName: $fn}')"

      - name: Call finishMatch
        run: |
          curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -H "X-Authorization: $AUTH_HEADER" \
          -d "$(echo $PAYLOAD_BASE | jq --arg fn finishMatch '. + {FunctionName: $fn}')"
